### ISSUE TITLE
timeTest.m is no longer working 

### ISSUE THREAD

**Issue by iron76** [robotology/mex-wholebodymodel#60]
I was trying to use the timeTest.m but it seems that it has been no longer updated. The error I am getting is:

```
Error in number of arguments, check docs

Error in timeTest (line 26)
    M = wholeBodyModel('mass-matrix',q);
```

I think it would be useful include it among tests since it always good to have an idea of the time required to make basic computations. As for now, I would not require stringent limit on computations.

**Comment by naveenoid** [comment]
Fix presented here : 
https://github.com/robotology/mex-wholebodymodel/commit/1a58d5e77920dfbfa3a4f66f782536d277082dcf

It assumes that launching happens from timeTest folder. The optimised mode no longer presents any significant time advantage since the computation of worldFrame is no longer performed with inverseKinematics implicitly in normal mode.
